name: CI

on:
  workflow_dispatch:
    inputs:
      version:
        default: 'v20.1.8.0'
        description: 'Package version'
        type: string
        required: true

jobs:
  build_image:
    name: Build ${{ matrix.platform }} image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
          - arm64
          - loong64
          - ppc64le
          - riscv64
          - s390x

    steps:
      - uses: actions/checkout@v5
        with:
          repository: mayeut/static-clang-images
          ref: ${{ github.event.inputs.version }}

      - name: Get clang version
        id: llvm-version
        run: |
          sed -i "s@alpine:@ghcr.io/loong64/alpine:@g" Dockerfile
          sed -i "s@ARG XX_VERSION=.*@ARG XX_VERSION=1.8.0@g" Dockerfile
          echo "version=$(cat llvm-version)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        if: matrix.platform != 'amd64'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/${{ matrix.platform }}
          load: true
          push: false
          build-args: |
            LLVM_VERSION=${{ steps.llvm-version.outputs.version }}
          tags: static-clang:latest
          outputs: type=local,dest=./binaries
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/static-clang-builder:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/static-clang-builder:buildcache,mode=max,compression=zstd,compression-level=22

      - name: Prepare Archive
        run: tar cf - -C binaries/opt --owner 0 --group 0 clang | xz -9e -T0 > binaries/static-clang-linux-${{ matrix.platform }}.tar.xz

      # TODO add some basic tests here

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: static-clang-${{ matrix.platform }}
          path: binaries/static-clang-linux-${{ matrix.platform }}.tar.xz
          if-no-files-found: error

      - name: Push image by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/${{ matrix.platform }}
          push: true
          outputs: type=image,name=ghcr.io/${{ github.repository_owner }}/static-clang,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.platform }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: Merge image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs:
      - build_image
    steps:
      - uses: actions/checkout@v5
      - name: Download digests
        uses: actions/download-artifact@v5
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/static-clang
          tags: |
            type=raw,value=edge
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}.{{patch}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf 'ghcr.io/${{ github.repository_owner }}/static-clang@sha256:%s ' *)

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build_image
    steps:
      - uses: actions/checkout@v5

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: binaries
          pattern: static-clang-*
          merge-multiple: true

      - name: Create sha256sums
        run: sha256sum *.tar.xz > sha256sums.txt
        working-directory: binaries

      - name: Display shasums
        run: cat binaries/sha256sums.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: 'binaries/*'